import type { Metadata } from "next";
import { Crimson_Text, DM_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header/header";
import { Footer } from "@/components/layout/footer";

export const crimsonText = Crimson_Text({
  subsets: ["latin"],
  weight: ["400"], // regular
  variable: "--font-crimson-text",
});

export const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500"], // 400 = regular, 500 = medium
  variable: "--font-dm-sans",
});

export const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400"], // regular
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonText.variable} ${dmSans.variable} ${robotoMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
